### PR TITLE
Option to disable runtime cancel button checking.

### PR DESCRIPTION
**Pull request by thinkl33t**
Added a config variable that disables runtime checking of the i2c
display, for those of us who have trouble with our lasers freezing
up part way through a job

### CODE REVIEW

**Comment by matthijskooijman** [comment]
I haven't actually tried this code yet, but wouldn't it make sense to also remove the `[cancel]` from the display if the button isn't being checked? Or can you still use the cancel button by keeping it pressed for a longer period of time or something?

**Comment by matthijskooijman** [comment]
Also, this PR didn't update the CHANGELOG file. Is the intention to update the CHANGELOG along with the commit that introduces a change?

**Comment by peteruithoven** [comment]
Yes the changelog should defiantly be changed. Removing [cancel] might be tricky because that also requires updating the firmware on the Arduino.

**Comment by jrv** [comment]
The text on the I2C display is generated by the mbed, so yes, it would be possible to remove [cancel] from the display too. We await your patch...

**Pull request merged**
